# Site settings
title: Saharaying's Blog
email: saharaying@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tech rails ruby mongodb javascript css
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saharaying.com" # the base hostname & protocol for your site
github_username:  saharaying

# Build settings
markdown: kramdown
