# Site settings
title: Saharaying的博客
email: saharaying@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rails Ruby MongoDB Javascript CSS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saharaying.com" # the base hostname & protocol for your site
github_username:  saharaying

# Build settings
markdown: kramdown
